version: "3.0"

services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile.web
    command: "/app/bin/docker/web-entrypoint.sh"
    ports:
      - "4000:4000"
      - "8000:8000"
    depends_on:
      - db
    hostname: quiz-web
    environment:
      MIX_ENV: "dev"
      POSTGRES_HOST: "db"
      POSTGRES_DB: "quiz_dev"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - .:/app
      - ./docker/deps:/app/deps
      - ./docker/_build:/app/_build
      - ./docker/node_modules:/app/assets/node_modules

  db:
    image: postgres:9.6.2
    environment:
      POSTGRES_DB: "quiz_dev"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"

    volumes:
      - db-volume:/var/lib/postgresql/data

volumes:
  db-volume:
